### ISSUE TITLE
Sending absolute positions for mouse movement

### ISSUE THREAD

**Issue by alin256** [thewh1teagle/zero-hid#11]
In the current implementation, only relative mouse positioning is exposed to Python.

Is it possible to send absolute positions? 

If there is a buffer structure reference that you are aware of I can implement the bindings and send a PR.

**Comment by thewh1teagle** [comment]
Hi
Currently only relative position supported.




As far as I know, `hid` descriptors allow only relative / absolute positioning per one device.

device - mouse  / keyboard.
we create them using the gadget module in Linux with the script inside [usb_gadget](https://github.com/thewh1teagle/zero-hid/tree/main/usb_gadget)

So if we want to support both relative and absolute position for mouse,
we should create two different devices, and send the command to that specific device from python.

I don't have rpi zero to try it on, 
but as starting point I would try to modify the script of `usb_gadget` and configure the descriptor to send only absolute positions for mouse.
after you change just run the installer script there for reinstall it and check it with the library.

**Comment by alin256** [comment]
For future us. Here is an example of supposedly absolute positioning. 

https://gist.github.com/bitboy85/cdcd0e7e04082db414b5f1d23ab09005

**Comment by thewh1teagle** [comment]
@alin256 
Do you have idea if it's possible to configure HID report which will allow both relative or absolute positioning by choice in each report?

**Comment by sakar111** [comment]
Hi,

I tried commenting out the relative mouse section from the init_usb_gadget function, and while everything else is working, the absolute movement is still behaving as if it were relative. However, there are some differences compared to the original relative movement behavior.

Any solution to make absolute work?

**Comment by sakar111** [comment]
![image](https://github.com/thewh1teagle/zero-hid/assets/47787401/0f2030f9-5bd1-401b-8963-47b396f22f5a)

I am trying this on raspberry pi zero 2W. I tested it as it is without changing anything. After running the installer hidg2 is missing.

![image](https://github.com/thewh1teagle/zero-hid/assets/47787401/41749470-b7fb-45ae-bd2b-53cfc7f7947e)

In the init_usb_gadgeta the mouse absolute section was not able to create 'functions/hid.mouse_absolute' directory.

**Comment by sakar111** [comment]
@thewh1teagle 
`sandbox@raspberrypi:~/Documents/rpi_hid/zero-hid/usb_gadget $ sudo ./installer.bash 
dtoverlay=dwc2
dwc2
libcomposite
+ set -u
+ modprobe libcomposite
+ cd /sys/kernel/config/usb_gadget/
+ mkdir -p g1
+ cd g1
+ echo 0x1d6b
+ echo 0x0104
+ echo 0x0100
+ echo 0x0200
+ STRINGS_DIR=strings/0x409
+ mkdir -p strings/0x409
+ echo 6b65796d696d6570690
+ echo tinypilot
+ echo 'Multifunction USB Device'
+ KEYBOARD_FUNCTIONS_DIR=functions/hid.keyboard
+ mkdir -p functions/hid.keyboard
+ echo 1
+ echo 1
+ echo 8
++ mktemp
+ D=/tmp/tmp.NiBlhKQ2hk
+ echo -ne '\x05\x01'
+ echo -ne '\x09\x06'
+ echo -ne '\xA1\x01'
+ echo -ne '\x05\x08'
+ echo -ne '\x19\x01'
+ echo -ne '\x29\x03'
+ echo -ne '\x15\x00'
+ echo -ne '\x25\x01'
+ echo -ne '\x75\x01'
+ echo -ne '\x95\x03'
+ echo -ne '\x91\x02'
+ echo -ne '\x09\x4B'
+ echo -ne '\x95\x01'
+ echo -ne '\x91\x02'
+ echo -ne '\x95\x04'
+ echo -ne '\x91\x01'
+ echo -ne '\x05\x07'
+ echo -ne '\x19\xE0'
+ echo -ne '\x29\xE7'
+ echo -ne '\x95\x08'
+ echo -ne '\x81\x02'
+ echo -ne '\x75\x08'
+ echo -ne '\x95\x01'
+ echo -ne '\x81\x01'
+ echo -ne '\x19\x00'
+ echo -ne '\x29\x91'
+ echo -ne '\x26\xFF\x00'
+ echo -ne '\x95\x06'
+ echo -ne '\x81\x00'
+ echo -ne '\xC0'
+ cp /tmp/tmp.NiBlhKQ2hk functions/hid.keyboard/report_desc
+ MOUSE_RELATIVE_FUNCTIONS_DIR=functions/hid.mouse_relative
+ mkdir -p functions/hid.mouse_relative
+ echo 0
+ echo 0
+ echo 7
++ mktemp
+ D=/tmp/tmp.S9fpJJ61Th
+ echo -ne '\x05\x01'
+ echo -ne '\x09\x02'
+ echo -ne '\xA1\x01'
+ echo -ne '\x05\x09'
+ echo -ne '\x19\x01'
+ echo -ne '\x29\x08'
+ echo -ne '\x15\x00'
+ echo -ne '\x25\x01'
+ echo -ne '\x95\x08'
+ echo -ne '\x75\x01'
+ echo -ne '\x81\x02'
+ echo -ne '\x05\x01'
+ echo -ne '\x09\x30'
+ echo -ne '\x09\x31'
+ echo -ne '\x15\x81'
+ echo -ne '\x25\x7f'
+ echo -ne '\x75\x08'
+ echo -ne '\x95\x02'
+ echo -ne '\x81\x06'
+ echo -ne '\x09\x38'
+ echo -ne '\x15\x81'
+ echo -ne '\x25\x7F'
+ echo -ne '\x75\x08'
+ echo -ne '\x95\x01'
+ echo -ne '\x81\x06'
+ echo -ne '\x05\x0C'
+ echo -ne '\x0A\x38\x02'
+ echo -ne '\x15\x81'
+ echo -ne '\x25\x7F'
+ echo -ne '\x75\x08'
+ echo -ne '\x95\x01'
+ echo -ne '\x81\x06'
+ echo -ne '\xC0'
+ cp /tmp/tmp.S9fpJJ61Th functions/hid.mouse_relative/report_desc
+ MOUSE_ABSOLUTE_FUNCTIONS_DIR=functions/hid.mouse_absolute
+ mkdir -p functions/hid.mouse_absolute
+ echo 0
+ echo 0
+ echo 7
++ mktemp
+ D=/tmp/tmp.odthqKkuMB
+ echo -ne '\x05\x01'
+ echo -ne '\x09\x02'
+ echo -ne '\xA1\x01'
+ echo -ne '\x05\x09'
+ echo -ne '\x19\x01'
+ echo -ne '\x29\x08'
+ echo -ne '\x15\x00'
+ echo -ne '\x25\x01'
+ echo -ne '\x95\x08'
+ echo -ne '\x75\x01'
+ echo -ne '\x81\x02'
+ echo -ne '\x05\x01'
+ echo -ne '\x09\x30'
+ echo -ne '\x09\x31'
+ echo -ne '\x15\x00'
+ echo -ne '\x26\xff\x7f'
+ echo -ne '\x75\x10'
+ echo -ne '\x95\x02'
+ echo -ne '\x81\x02'
+ echo -ne '\x09\x38'
+ echo -ne '\x15\x81'
+ echo -ne '\x25\x7F'
+ echo -ne '\x75\x08'
+ echo -ne '\x95\x01'
+ echo -ne '\x81\x06'
+ echo -ne '\x05\x0C'
+ echo -ne '\x0A\x38\x02'
+ echo -ne '\x15\x81'
+ echo -ne '\x25\x7F'
+ echo -ne '\x75\x08'
+ echo -ne '\x95\x01'
+ echo -ne '\x81\x06'
+ echo -ne '\xC0'
+ cp /tmp/tmp.odthqKkuMB functions/hid.mouse_absolute/report_desc
+ CONFIG_INDEX=1
+ CONFIGS_DIR=configs/c.1
+ mkdir -p configs/c.1
+ echo 250
+ CONFIGS_STRINGS_DIR=configs/c.1/strings/0x409
+ mkdir -p configs/c.1/strings/0x409
+ echo 'Config 1: ECM network'
+ ln -s functions/hid.keyboard configs/c.1/
+ ln -s functions/hid.mouse_relative configs/c.1/
+ ln -s functions/hid.mouse_absolute configs/c.1/
+ ls /sys/class/udc
+ chmod 777 /dev/hidg0
chmod: cannot access '/dev/hidg0': No such file or directory
Installed usb gadget, You should reboot now
Do you want to reboot? (Y/n) `

![image](https://github.com/thewh1teagle/zero-hid/assets/47787401/f6cb0727-e717-4884-aa06-1b7189004388)

**Comment by thewh1teagle** [comment]
Strange. 
Can you copy paste blocks from https://github.com/thewh1teagle/zero-hid/blob/main/usb_gadget/init_usb_gadget
And try to figure out why it doesn't create the folder?
even just try to create the folder manually there

**Comment by sakar111** [comment]
Its working well now. My /etc/rc.local file was corrupt. Thanks.

**Comment by thewh1teagle** [comment]
@sakar111 
congrats!
I hope that now the scripts working fine
