### ISSUE TITLE
Typo in Homepage on PyPI

### ISSUE THREAD

**Issue by michalpokusa** [thewh1teagle/zero-hid#14]
Hi, thanks a lot for this lib, helped a lot in my recent tinkering with Pi Zero.

I came across this lib onb PyPI, but when I wanted to go to Homepage I got 404 GitHub page. Nevertheless I managed to find this repo.

It seems that there is a typo in the package configuration, so instead of pointing to `https://pypi.org/project/zero-hid/` it points to `https://pypi.org/project/zero_hid/` with **underscore instead of hyphen**.

This is not strictly a issue with the lib, but I wasn't able to come up with any other way to report that, mainly because you set the email to a mock one.

Take care and happy new year 🎆

**Comment by thewh1teagle** [comment]
Thanks for letting know, I'll fix it
