### ISSUE TITLE
Capslock status of host

### ISSUE THREAD

**Issue by samca208** [thewh1teagle/zero-hid#15]
When sending characters thru keyboard emulation, and the host computer has a secondary keyboard installed with capslock ON. The characters sent from the Raspberry PI have the case invented. Example sending 'Hello' will result in 'hELLO'. Is there any feature to counter measure this?

**Comment by thewh1teagle** [comment]
@samca208 
afaik there's no way to change it. 
Imagine that you connect another real second keyboard to the computer, then turn ON the CapsLock on one of them.
The characters case will change for both
