### ISSUE TITLE
Enable Azerty

### ISSUE THREAD

**Issue by Suniron** [thewh1teagle/zero-hid#18]
Hey there,

I don't understand how can i enable the AZERTY output, for kerboard `type` method.

Thank's in advance

**Comment by thewh1teagle** [comment]
Why should you enable AZERTY layout? 
Specifying layout is important when you have pysical keys
But you send the keys directly
I'm not sure how you would use it

**Comment by Suniron** [comment]
My problem is when I do `k.type("azerty")` in the Python script, **qwerty** is printed on the linked device.

So, does the keyboard layout be configured on the output device ?

If it's true, it's not easy to switch between multiple devices..

**Comment by Suniron** [comment]
Ok, i found my solution, it was to set the layout like this:

```python
with Keyboard() as k:
    k.set_layout('FR')
    k.type("My text in azerty")
```
