### ISSUE TITLE
do it work with ...

### ISSUE THREAD

**Issue by gsilos** [thewh1teagle/zero-hid#24]
Raspberry Pi Zero 2 W Rev 1.0

fs@kayak:~/code/hid $ uname -a
Linux kayak 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
fs@kayak:~/code/hid $ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

?

**Comment by thewh1teagle** [comment]
It worked?
